services:
  api:
    build: .
    ports:
      - "5254:5254"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Server=sqlserver;Database=Petminder;User Id=sa;Password=YourStrong!Passw0rd;Encrypt=False;
      - ASPNETCORE_URLS=http://*:5254  # Ensures the API runs on port 5254 inside the container
    depends_on:
      - sqlserver
    restart: always  # Optional: Ensures API restarts if it fails

  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=YourStrong!Passw0rd
    ports:
      - "1433:1433"
    restart: always  # Optional: Ensures SQL Server restarts if it fails
