# Use the official .NET SDK image to build and publish the app
FROM mcr.microsoft.com/dotnet/aspnet:8.0 AS base
WORKDIR /app
EXPOSE 5254

# Use the official build image
FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build
WORKDIR /src
COPY ["PetMinder-API.csproj", "./"]
RUN dotnet restore "./PetMinder-API.csproj"
COPY . .
WORKDIR "/src"
RUN dotnet build "PetMinder-API.csproj" -c Release -o /app/build

FROM build AS publish
RUN dotnet publish "PetMinder-API.csproj" -c Release -o /app/publish

# Use the base image to run the app
FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "PetMinder-API.dll"]
