name: Deploy to Production

on:
  schedule:
    - cron: "0 0 * * *"  # This runs at 00:00 UTC every day
  push:
    branches:
      - Production

permissions:
  id-token: write
  contents: read

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code from the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up .NET Core (adjust if you're using a different version)
      - name: Set up .NET Core
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 8.0.x

      # Step 3: Restore dependencies (for the specific project)
      - name: Restore dependencies
        run: dotnet restore ADD-NETCore-Prototype/PetMinder-API.csproj

      # Step 4: Build the ADD-NETCore-Prototype project (without restoring again)
      - name: Build
        run: dotnet build ADD-NETCore-Prototype/PetMinder-API.csproj --no-restore

      # Step 5: Run unit tests for the entire project or specific folder
      - name: Run tests
        run: |
          dotnet test ADD-NETCore-Prototype.Tests/PetMinder-API.Tests.csproj --no-build --verbosity normal || true
      
      # Step 6: Publish the ADD-NETCore-Prototype project to create deployment artifacts
      - name: Publish application
        run: dotnet publish ADD-NETCore-Prototype/PetMinder-API.csproj --configuration Release --output ./publish-directory

      # Step 7: Log contents of the publish directory to ensure files are available
      - name: Verify publish directory contents
        run: ls -la ./publish-directory

      # Step 8: Login to Azure
      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_FF59F2158E59457C8400C49A14DCEC33 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_108C598E6480479F86B36BD2506B0EEC }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_AA5F3C4C6FC84773B3CC445560EB036D }}

      # Step 9: Deploy to Azure Web App
      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'petminder-production-API'
          slot-name: 'Production'
          package: ./publish-directory
