name: Deploy to Production

on:
  # Optional: Trigger on push to the Production branch
  push:
    branches:
      - production

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code from the repository
      - name: Checkout code
        uses: actions/checkout@v2

      # Step 2: Set up .NET Core (adjust if you're using a different version)
      - name: Set up .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 8.0.x

      # Step 3: Restore dependencies (for the entire repo or just for the specific project)
      - name: Restore dependencies
        run: dotnet restore ADD-NETCore-Prototype

      # Step 4: Build the ADD-NETCore-Prototype project (without restoring again)
      - name: Build
        run: dotnet build ADD-NETCore-Prototype --no-restore

      # Step 5: Run unit tests for the entire project or specific folder
      - name: Run tests
        run: |
          dotnet test ADD-NETCore-Prototype.Tests/ADD-NETCore-Prototype.Tests.csproj --no-build --verbosity normal || true

      # Step 6: Publish the ADD-NETCore-Prototype project to create deployment artifacts
      - name: Publish application
        run: dotnet publish ADD-NETCore-Prototype --configuration Release --output ./publish-directory

      # Step 7: Deploy to Azure Web App (Acceptance)
      - name: Deploy to Azure Web App (Acceptance)
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ secrets.PETMINDER_API_PRODUCTION }}
          publish-profile: ${{ secrets.AZURE_PUBLISH_PROFILE_PRODUCTION }}
          package: ./publish-directory
