name: Build and deploy ASP.Net Core app to Azure Web App - petminder-production-API

on:
  push:
    branches:
      - Production
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.x'

      # Target the specific project file for ADD-NETCore-Prototype
      - name: Build ADD-NETCore-Prototype
        run: dotnet build ADD-NETCore-Prototype/PetMinder-API.csproj --configuration Release --output ./API_Publish

      - name: Publish ADD-NETCore-Prototype
        run: dotnet publish ADD-NETCore-Prototype/PetMinder-API.csproj -c Release --output ./API_Publish

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: .net-api
          path: ./API_Publish  # Only package the API from ADD-NETCore-Prototype

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write #This is required for requesting the JWT

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: .net-api  # Download the specific API artifact
      
      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_FF59F2158E59457C8400C49A14DCEC33 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_108C598E6480479F86B36BD2506B0EEC }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_AA5F3C4C6FC84773B3CC445560EB036D }}

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'petminder-production-API'
          slot-name: 'Production'
          package: './API_Publish'  # Ensure only the API from ADD-NETCore-Prototype is deployed
