name: Deploy to Production

on:
  push:
    branches:
      - Production

  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write  # Grant permission to request an OIDC token
      contents: read   # Permission to read repository contents

    steps:
      # Step 1: Checkout the code from the repository
      - name: Checkout code
        uses: actions/checkout@v2

      # Step 2: Set up .NET Core (adjust if you're using a different version)
      - name: Set up .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 8.0.x

      # Step 3: Restore dependencies
      - name: Restore dependencies
        run: dotnet restore ADD-NETCore-Prototype

      # Step 4: Build the project
      - name: Build
        run: dotnet build ADD-NETCore-Prototype --no-restore

      # Step 5: Run unit tests
      - name: Run tests
        run: |
          dotnet test ADD-NETCore-Prototype.Tests/ADD-NETCore-Prototype.Tests.csproj --no-build --verbosity normal || true

      # Step 6: Publish the project
      - name: Publish application
        run: dotnet publish ADD-NETCore-Prototype --configuration Release --output ./publish-directory

      # Step 7: Login to Azure
      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_FF59F2158E59457C8400C49A14DCEC33 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_108C598E6480479F86B36BD2506B0EEC }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_AA5F3C4C6FC84773B3CC445560EB036D }}

      # Step 8: Deploy to Azure Web App (Production)
      - name: Deploy to Azure Web App (Production)
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'petminder-production-API'
          package: ./publish-directory
