name: Deploy to Acceptance

# Trigger the workflow on every push to the main branch
on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout the code from the repository
    - name: Checkout code
      uses: actions/checkout@v2

    # Step 2: Set up .NET Core (adjust this if you're using a different stack)
    - name: Set up .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 8.0.x

    # Step 3: Build the project
    - name: Build the app
      run: dotnet build


    -

    # Step 4: Deploy to Azure Web App (Acceptance)
    - name: Deploy to Azure Web App (Acceptance)
      uses: azure/webapps-deploy@v2
      with:
        app-name: ${{ secrets.AZURE_APP_NAME_ACCEPTANCE }}
        publish-profile: ${{ secrets.AZURE_PUBLISH_PROFILE_ACCEPTANCE }}
