name: Deploy to Acceptance

# Trigger the workflow on a schedule (every day at midnight UTC)
on:
  schedule:
    - cron: "0 0 * * *"  # This runs at 00:00 UTC every day

  # Optional: Trigger on push to the main branch
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code from the repository
      - name: Checkout code
        uses: actions/checkout@v2

      # Step 2: Set up .NET Core (adjust if you're using a different version)
      - name: Set up .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 8.0.x

      # Step 3: Restore dependencies
      - name: Restore dependencies
        run: dotnet restore

      # Step 4: Build the project (without restoring again)
      - name: Build
        run: dotnet build --no-restore

      # Step 5: Run unit tests
      - name: Run tests
        run: |
          dotnet test PetMinder-APITests/PetMinder-APITests.csproj --no-build --verbosity normal || true

      # Step 6: Clean up and retain only the ADD-NETCore-Prototype directory
      - name: Retain ADD-NETCore-Prototype directory
        run: |
          mkdir -p temp-directory
          mv ADD-NETCore-Prototype temp-directory/
          rm -rf ./*
          mv temp-directory/ADD-NETCore-Prototype ./
          rm -rf temp-directory

      # Step 7: Publish the ADD-NETCore-Prototype project to create deployment artifacts
      - name: Publish application
        run: dotnet publish ADD-NETCore-Prototype --configuration Release --output ./publish-directory

      # Step 8: Deploy to Azure Web App (Acceptance)
      - name: Deploy to Azure Web App (Acceptance)
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ secrets.PETMINDER_API_ACCEPTANCE }}
          publish-profile: ${{ secrets.AZURE_PUBLISH_PROFILE_ACCEPTANCE }}
          package: ./publish-directory