name: Deploy to Production

on:
  schedule:
    - cron: "0 0 * * *"  # This runs at 00:00 UTC every day
  push:
    branches:
      - Production

permissions:
  id-token: write
  contents: read

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3  # Updated to v3

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v3  # Updated to v3
        with:
          dotnet-version: 8.0.x

      - name: Restore dependencies
        run: dotnet restore ADD-NETCore-Prototype/PetMinder-API.csproj

      - name: Build
        run: dotnet build ADD-NETCore-Prototype/PetMinder-API.csproj --no-restore

      - name: Run tests
        run: |
          dotnet test ADD-NETCore-Prototype.Tests/PetMinder-API.Tests.csproj --no-build --verbosity normal || true

      - name: Publish application
        run: dotnet publish ADD-NETCore-Prototype/PetMinder-API.csproj --configuration Release --output ./publish-directory

      - name: Verify publish directory contents
        run: ls -la ./publish-directory

      # Extra check before uploading artifact
      - name: Verify publish directory before uploading artifact
        run: ls -la ./publish-directory

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: net-app
          path: ./publish-directory

  deploy:
    runs-on: ubuntu-latest
    needs: build-and-deploy
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: net-app

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_FF59F2158E59457C8400C49A14DCEC33 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_108C598E6480479F86B36BD2506B0EEC }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_AA5F3C4C6FC84773B3CC445560EB036D }}

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'petminder-production-API'
          slot-name: 'Production'
          package: ./publish-directory
