name: .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    - name: Restore dependencies
      run: dotnet restore --verbosity minimal

    - name: Build Solution
      run: dotnet build PetMinder-API.sln --no-restore --verbosity normal

    - name: Run tests
      run: |
        dotnet test PetMinder-APITests/PetMinder-APITests.csproj --no-build --verbosity normal || true
